all:
  vars:
    control_plane_endpoint: 10.0.1.100
    load_balancer_ip_pool:
      - 10.0.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.0.1.85, mac: '18:60:24:23:26:17', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 10.0.1.86, mac: 'e4:e7:49:50:e8:0a', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 10.0.1.87, mac: '98:e7:f4:ba:91:f2', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 10.0.1.95, mac: '10:e7:c6:0e:62:1d', disk: sda, network_interface: eno1}
