elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.leepope.cc"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.leepope.cc
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.leepope.cc
      server_name: leepope.cc

dendrite:
  dendrite_config:
    global:
      server_name: matrix.leepope.cc
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.leepope.cc
    tls:
      - hosts:
          - matrix.leepope.cc
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
